package currency

var currencies = map[string]*Currency{
	"AED": &Currency{
		Code:             "AED",
		Symbol:           "د.إ.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"AFN": &Currency{
		Code:             "AFN",
		Symbol:           "؋",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "$n-",
	},
	"ALL": &Currency{
		Code:             "ALL",
		Symbol:           "Lek",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n$",
		NegativePattern:  "-n$",
	},
	"AMD": &Currency{
		Code:             "AMD",
		Symbol:           "դր.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"ARS": &Currency{
		Code:             "ARS",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "$-n",
	},
	"AUD": &Currency{
		Code:             "AUD",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"AZN": &Currency{
		Code:             "AZN",
		Symbol:           "ман.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"BAM": &Currency{
		Code:             "BAM",
		Symbol:           "KM",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"BDT": &Currency{
		Code:             "BDT",
		Symbol:           "৳",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 2},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"BGN": &Currency{
		Code:             "BGN",
		Symbol:           "лв.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"BHD": &Currency{
		Code:             "BHD",
		Symbol:           "د.ب.‏",
		DecimalDigits:    3,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"BND": &Currency{
		Code:             "BND",
		Symbol:           "$",
		DecimalDigits:    0,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"BOB": &Currency{
		Code:             "BOB",
		Symbol:           "$b",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"BRL": &Currency{
		Code:             "BRL",
		Symbol:           "R$",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "-$ n",
	},
	"BYR": &Currency{
		Code:             "BYR",
		Symbol:           "р.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"BZD": &Currency{
		Code:             "BZD",
		Symbol:           "BZ$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"CAD": &Currency{
		Code:             "CAD",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"CHF": &Currency{
		Code:             "CHF",
		Symbol:           "fr.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   "'",
		PositivePattern:  "$ n",
		NegativePattern:  "$-n",
	},
	"CLP": &Currency{
		Code:             "CLP",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "-$ n",
	},
	"CNY": &Currency{
		Code:             "CNY",
		Symbol:           "¥",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "$-n",
	},
	"COP": &Currency{
		Code:             "COP",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"CRC": &Currency{
		Code:             "CRC",
		Symbol:           "₡",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"CSD": &Currency{
		Code:             "CSD",
		Symbol:           "Дин.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"CZK": &Currency{
		Code:             "CZK",
		Symbol:           "Kč",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"DKK": &Currency{
		Code:             "DKK",
		Symbol:           "kr.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"DOP": &Currency{
		Code:             "DOP",
		Symbol:           "RD$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"DZD": &Currency{
		Code:             "DZD",
		Symbol:           "د.ج.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"EEK": &Currency{
		Code:             "EEK",
		Symbol:           "kr",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"EGP": &Currency{
		Code:             "EGP",
		Symbol:           "ج.م.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"ETB": &Currency{
		Code:             "ETB",
		Symbol:           "ETB",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"EUR": &Currency{
		Code:             "EUR",
		Symbol:           "€",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"GBP": &Currency{
		Code:             "GBP",
		Symbol:           "£",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"GEL": &Currency{
		Code:             "GEL",
		Symbol:           "Lari",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"GTQ": &Currency{
		Code:             "GTQ",
		Symbol:           "Q",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"HKD": &Currency{
		Code:             "HKD",
		Symbol:           "HK$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"HNL": &Currency{
		Code:             "HNL",
		Symbol:           "L.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"HRK": &Currency{
		Code:             "HRK",
		Symbol:           "kn",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"HUF": &Currency{
		Code:             "HUF",
		Symbol:           "Ft",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"IDR": &Currency{
		Code:             "IDR",
		Symbol:           "Rp",
		DecimalDigits:    0,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"ILS": &Currency{
		Code:             "ILS",
		Symbol:           "₪",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$-n",
	},
	"INR": &Currency{
		Code:             "INR",
		Symbol:           "ரூ",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 2},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"IQD": &Currency{
		Code:             "IQD",
		Symbol:           "د.ع.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"IRR": &Currency{
		Code:             "IRR",
		Symbol:           "ريال",
		DecimalDigits:    2,
		DecimalSeparator: "/",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"ISK": &Currency{
		Code:             "ISK",
		Symbol:           "kr.",
		DecimalDigits:    0,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"JMD": &Currency{
		Code:             "JMD",
		Symbol:           "J$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"JOD": &Currency{
		Code:             "JOD",
		Symbol:           "د.ا.‏",
		DecimalDigits:    3,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"JPY": &Currency{
		Code:             "JPY",
		Symbol:           "¥",
		DecimalDigits:    0,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"KES": &Currency{
		Code:             "KES",
		Symbol:           "S",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"KGS": &Currency{
		Code:             "KGS",
		Symbol:           "сом",
		DecimalDigits:    2,
		DecimalSeparator: "-",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"KHR": &Currency{
		Code:             "KHR",
		Symbol:           "៛",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "n$",
		NegativePattern:  "-n$",
	},
	"KRW": &Currency{
		Code:             "KRW",
		Symbol:           "₩",
		DecimalDigits:    0,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"KWD": &Currency{
		Code:             "KWD",
		Symbol:           "د.ك.‏",
		DecimalDigits:    3,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"KZT": &Currency{
		Code:             "KZT",
		Symbol:           "Т",
		DecimalDigits:    2,
		DecimalSeparator: "-",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"LAK": &Currency{
		Code:             "LAK",
		Symbol:           "₭",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "n$",
		NegativePattern:  "(n$)",
	},
	"LBP": &Currency{
		Code:             "LBP",
		Symbol:           "ل.ل.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"LKR": &Currency{
		Code:             "LKR",
		Symbol:           "රු.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"LTL": &Currency{
		Code:             "LTL",
		Symbol:           "Lt",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"LVL": &Currency{
		Code:             "LVL",
		Symbol:           "Ls",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "$ n",
		NegativePattern:  "-$ n",
	},
	"LYD": &Currency{
		Code:             "LYD",
		Symbol:           "د.ل.‏",
		DecimalDigits:    3,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "$n-",
	},
	"MAD": &Currency{
		Code:             "MAD",
		Symbol:           "د.م.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"MKD": &Currency{
		Code:             "MKD",
		Symbol:           "ден.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"MNT": &Currency{
		Code:             "MNT",
		Symbol:           "₮",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n$",
		NegativePattern:  "-n$",
	},
	"MOP": &Currency{
		Code:             "MOP",
		Symbol:           "MOP",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"MVR": &Currency{
		Code:             "MVR",
		Symbol:           "ރ.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "n $",
		NegativePattern:  "n $-",
	},
	"MXN": &Currency{
		Code:             "MXN",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"MYR": &Currency{
		Code:             "MYR",
		Symbol:           "RM",
		DecimalDigits:    0,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"NIO": &Currency{
		Code:             "NIO",
		Symbol:           "N",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$-n",
	},
	"NOK": &Currency{
		Code:             "NOK",
		Symbol:           "kr",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"NPR": &Currency{
		Code:             "NPR",
		Symbol:           "रु",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"NZD": &Currency{
		Code:             "NZD",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"OMR": &Currency{
		Code:             "OMR",
		Symbol:           "ر.ع.‏",
		DecimalDigits:    3,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"PAB": &Currency{
		Code:             "PAB",
		Symbol:           "B/.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"PEN": &Currency{
		Code:             "PEN",
		Symbol:           "S/.",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"PHP": &Currency{
		Code:             "PHP",
		Symbol:           "Php",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"PKR": &Currency{
		Code:             "PKR",
		Symbol:           "Rs",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "$n-",
	},
	"PLN": &Currency{
		Code:             "PLN",
		Symbol:           "zł",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"PYG": &Currency{
		Code:             "PYG",
		Symbol:           "Gs",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"QAR": &Currency{
		Code:             "QAR",
		Symbol:           "ر.ق.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"RON": &Currency{
		Code:             "RON",
		Symbol:           "lei",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"RSD": &Currency{
		Code:             "RSD",
		Symbol:           "Din.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"RUB": &Currency{
		Code:             "RUB",
		Symbol:           "һ.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"RWF": &Currency{
		Code:             "RWF",
		Symbol:           "RWF",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "$ n",
		NegativePattern:  "$-n",
	},
	"SAR": &Currency{
		Code:             "SAR",
		Symbol:           "ر.س.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"SEK": &Currency{
		Code:             "SEK",
		Symbol:           "kr",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"SGD": &Currency{
		Code:             "SGD",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"SYP": &Currency{
		Code:             "SYP",
		Symbol:           "ل.س.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"THB": &Currency{
		Code:             "THB",
		Symbol:           "฿",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"TJS": &Currency{
		Code:             "TJS",
		Symbol:           "т.р.",
		DecimalDigits:    2,
		DecimalSeparator: ";",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"TMT": &Currency{
		Code:             "TMT",
		Symbol:           "m.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n$",
		NegativePattern:  "-n$",
	},
	"TND": &Currency{
		Code:             "TND",
		Symbol:           "د.ت.‏",
		DecimalDigits:    3,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"TRY": &Currency{
		Code:             "TRY",
		Symbol:           "TL",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"TTD": &Currency{
		Code:             "TTD",
		Symbol:           "TT$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
	"TWD": &Currency{
		Code:             "TWD",
		Symbol:           "NT$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "-$n",
	},
	"UAH": &Currency{
		Code:             "UAH",
		Symbol:           "₴",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n$",
		NegativePattern:  "-n$",
	},
	"USD": &Currency{
		Code:             "USD",
		Symbol:           "$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3, 0},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"UYU": &Currency{
		Code:             "UYU",
		Symbol:           "$U",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "($ n)",
	},
	"UZS": &Currency{
		Code:             "UZS",
		Symbol:           "сўм",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"VEF": &Currency{
		Code:             "VEF",
		Symbol:           "Bs. F.",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "$ n",
		NegativePattern:  "$ -n",
	},
	"VND": &Currency{
		Code:             "VND",
		Symbol:           "₫",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   ".",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"XOF": &Currency{
		Code:             "XOF",
		Symbol:           "XOF",
		DecimalDigits:    2,
		DecimalSeparator: ",",
		GroupSizes:       []int{3},
		GroupSeparator:   " ",
		PositivePattern:  "n $",
		NegativePattern:  "-n $",
	},
	"YER": &Currency{
		Code:             "YER",
		Symbol:           "ر.ي.‏",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$n-",
	},
	"ZAR": &Currency{
		Code:             "ZAR",
		Symbol:           "R",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$ n",
		NegativePattern:  "$-n",
	},
	"ZWL": &Currency{
		Code:             "ZWL",
		Symbol:           "Z$",
		DecimalDigits:    2,
		DecimalSeparator: ".",
		GroupSizes:       []int{3},
		GroupSeparator:   ",",
		PositivePattern:  "$n",
		NegativePattern:  "($n)",
	},
}
